# Generated by Django 3.1.2 on 2020-11-16 20:01

from django.db import migrations, models
import splash.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('category', models.IntegerField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to=splash.models.product_logo_path)),
                ('graphic', models.ImageField(upload_to=splash.models.product_graphic_path)),
            ],
        ),
    ]
