# Generated by Django 3.1.2 on 2020-11-16 22:19

from django.db import migrations, models
import splash.models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_sheet',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Concrete'), (2, 'Sound Control'), (3, 'Concrete Topping'), (4, 'Finish')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='graphic',
            field=models.ImageField(blank=True, null=True, upload_to=splash.models.product_graphic_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=splash.models.product_logo_path),
        ),
    ]
