# Generated by Django 3.1.2 on 2020-11-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0002_auto_20201116_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
