# Generated by Django 3.1.2 on 2021-03-02 00:37

from django.db import migrations, models
import splash.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0003_auto_20201116_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=list, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=splash.models.product_logo_path)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='uploads/')),
                ('alt', models.TextField()),
            ],
        ),
    ]
