# Generated by Django 3.1.2 on 2021-03-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0004_project_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='logo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='splash.project'),
        ),
    ]
