# Generated by Django 3.1.2 on 2021-03-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0005_auto_20210302_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='splash.project'),
        ),
    ]
